[tool.bumpversion]
current_version = "0.1.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
tag = true
sign_tags = false
tag_name = "r-v{new_version}"
tag_message = "Bump R version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump R version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "DESCRIPTION"
search = 'Version: {current_version}'
replace = 'Version: {new_version}'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = '## [Unreleased]'
replace = '''## [Unreleased]

## [{new_version}] - {now:%Y-%m-%d}'''
