# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_coursemap_wrappers", use_symbols = TRUE, package_name = "coursemap")

#' @usage NULL
#' @useDynLib coursemap, .registration = TRUE
NULL

#' Generate a course dependency map
generate_course_map <- function(input_dir, output_path, format, config_path) .Call(wrap__generate_course_map, input_dir, output_path, format, config_path)

#' Generate SVG content as string for inline embedding
generate_inline_svg <- function(input_dir, config_path) .Call(wrap__generate_inline_svg, input_dir, config_path)

#' Check if Graphviz is available
graphviz_available <- function() .Call(wrap__graphviz_available)

#' Get Graphviz version information
graphviz_info <- function() .Call(wrap__graphviz_info)

#' Parse documents in a directory and return metadata
parse_documents <- function(input_dir, config_path) .Call(wrap__parse_documents, input_dir, config_path)

#' Get configuration as list
get_config <- function(config_path) .Call(wrap__get_config, config_path)


# nolint end
